### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by webquali** [MobileAppTracking/phonegap-plugin#10]
Hello, 
I have problems with plugin when try build app by android studio.

Error:(229, 20) java: cannot find symbol
  symbol:   method checkForDeferredDeeplink(<anonymous com.mobileapptracker.MATDeeplinkListener>)
  location: variable mat of type com.mobileapptracker.MobileAppTracker
Error:(344, 28) java: method setGender in class com.mobileapptracker.MobileAppTracker cannot be applied to given types;
  required: int
  found: com.mobileapptracker.MATGender
  reason: actual argument com.mobileapptracker.MATGender cannot be converted to int by method invocation conversion
Error:(346, 28) java: method setGender in class com.mobileapptracker.MobileAppTracker cannot be applied to given types;
  required: int
  found: com.mobileapptracker.MATGender
  reason: actual argument com.mobileapptracker.MATGender cannot be converted to int by method invocation conversion
Error:(490, 57) java: cannot find symbol
  symbol:   method withAgencyId(java.lang.String)
  location: class com.mobileapptracker.MATPreloadData

**Comment by john-gu** [comment]
Hi, it seems like there's a version mismatch between the Android SDK library and the bridge code to Cordova. Can you confirm which SDK version is in your jniLibs folder? The latest is MobileAppTracker-3.11.0.jar.

**Comment by webquali** [comment]
Hello,

I have the same MobileAppTracker-3.11.0.jar. 
https://www.dropbox.com/s/w2pqfpze6abv8vn/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-09-15%2007.36.33.png?dl=0

**Comment by john-gu** [comment]
Could you also check if you have the current version of MATPlugin.java?
https://github.com/MobileAppTracking/phonegap-plugin/blob/master/src/android/com/mobileapptracking/MATPlugin.java

I would also try Synchronize or Sync Project with Gradle Files in Android Studio. It seems like some of the files are not updated for some reason. If you're still getting this error, please email me at johng@tune.com or we can look at it on Skype.

**Comment by webquali** [comment]
Please check your mail.

**Comment by john-gu** [comment]
Glad we could resolve this! Closing this issue, please let us know if you encounter any other issues.
