### ISSUE TITLE
Cordova does not send requests

### ISSUE THREAD

**Issue by DenisUA** [MobileAppTracking/phonegap-plugin#12]
Basically I'm trying to see any answer in admin panel. 
What I have done:
1. Installed cordova plugin add cordova-plugin-tune
2. Implemented code from https://developers.mobileapptracking.com/phonegap-plugin/
3. Created ios profile as it says here http://developers.mobileapptracking.com/creating-test-profile/
4. Got nothing in Actuals in menu

tested in simulator with Safari developer console, no requests at all. Even when I'm trying trigger any events from list (Like login/registration etc.)

**Comment by john-gu** [comment]
Hi @DenisUA, could you send a support request to support@tune.com and include your advertiser ID and app package name? We'll be able to look further into this with your account details specifically.

**Comment by DenisUA** [comment]
@john-gu ok done, thank you for the quick reply
