### ISSUE TITLE
latest version breaks previous interface

### ISSUE THREAD

**Issue by bisrael** [MobileAppTracking/phonegap-plugin#4]
The plugin was updated a few hours ago, removing the `initTracker` method and replacing it with `init`.

This immediately breaks every cordova app using the plugin.

As an API, you should respect [SemVer](http://semver.org/), and have either incremented the major version number or respect backwards compatibility.

Edit: Additionally, the javascript interfaces have changed dramatically, dropping support for user-submitted callbacks to check the status of cordova callbacks.

**Comment by john-gu** [comment]
Hi, we originally wanted to use a common version across our plugins to track which native SDK version they're on but you're right, we should have updated the major version number for the API changes we decided to make on the Cordova side, especially for auto-updated plugins.

**Comment by john-gu** [comment]
Version incremented to 4.0.0 in accordance with API backwards-incompatibility.
