### ISSUE TITLE
Separate `gaidwrapper` and `ifawrapper` into separate repos

### ISSUE THREAD

**Issue by bisrael** [MobileAppTracking/phonegap-plugin#7]
Currently when installing `com.mobileapptracking.matplugin`, cordova downloads everything inside the git repo.

This includes the "sub-projects" `gaidwrapper` and `ifawrapper`, both of which are installed as separate plugins through cordova.

This means every project using MAT will have an extra copy of each that isn't even used.

We should consider making those separate repositories to better reflect their separate plugin nature.

**Comment by john-gu** [comment]
Resolved with 5.0.0 release:
https://github.com/MobileAppTracking/phonegap-plugin/releases/tag/v5.0.0
