### ISSUE TITLE
How do you do deferred deep linking with the cordova sdk?

### ISSUE THREAD

**Issue by mike-roberts** [MobileAppTracking/phonegap-plugin#9]
I've been trying to figure this out as the documentation isn't very clear. I tried contacting a few people at Tune, but none were technical folk who could answer the question and just kept pointing me to various sales people who would answer the question with what the documentation says.

From what I gather it's not actually possible to use deferred deeplinking with this plugin.

checkForDeferredDeeplink is mapped to setDeferredDeeplink in the plugin, and nowhere is didReceiveDeepLink called. I'm wondering if this is as simple as just calling didReceiveDeeplink in the success callback of the SETDEFERREDDEEPLINK case.

**Comment by john-gu** [comment]
Hi Mike,

Currently, deferred deeplinks automatically try to open the native Activity that's set up for it when enabled (would have to be set up in the AndroidManifest).

It looks like we were a little overaggressive when we were cleaning up the public API from callbacks. Right now setDelegate receives the didReceiveDeeplink callback (amongst other callbacks), but we're not propagating that back up to the public JS call. We're doing a plugin update soon so we'll take a look at returning the deeplink value in a success callback.

Thanks,
John

**Comment by mike-roberts** [comment]
Any ideas on when you could get the didReceiveDeeplink to return to deeplink to the cordova plugin? In order for a cordova app to navigate to a page based on a deeplink, we need to have access to the deeplink.

**Comment by mike-roberts** [comment]
Seems like it's a pretty crucial feature for the cordova plugin, so that we know where to route a user after they download the app.

**Comment by john-gu** [comment]
Hi Mike,

We have an update planned for release within the next two weeks. We're investigating if we can return the callback in a better place than setDelegate as well.

Thanks,
John

**Comment by john-gu** [comment]
Hi Mike,

v4.1.0 has been released with Android deferred deeplinks fixed.

You can see a sample call here:
https://github.com/MobileAppTracking/phonegap-plugin/blob/master/example/index.html#L86

We will also be adding a Cordova example to our documentation.
